# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 02:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stardy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.BooleanField()),
                ('arrival_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('place', models.CharField(max_length=45)),
                ('introduction', models.CharField(max_length=45)),
                ('explanation', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_interests', to='stardy.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('eng_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField()),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_groups', to='stardy.Group')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_address',
            field=models.CharField(default='profile address', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=45),
        ),
        migrations.AddField(
            model_name='usersgroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupinterest',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_interests', to='stardy.Interest'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendence',
            name='users_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', to='stardy.UsersGroup'),
        ),
    ]
